/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TodoApp;

import TodoApp.controler.ProjectController;
import TodoApp.model.Project;
import java.sql.Connection;
import java.sql.Date;
import util.ConnectionFactory;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

    }
}
